name: NBUltimate
description: The ultimate NoteBlock plugin, includes a player and an editor for NBS files!
version: '${project.version}'
main: cc.cerial.nbultimate.NBUltimate
api-version: '1.20'
libraries:
  - net.raphimc:NoteBlockLib:2.0.5
  - net.kyori:adventure-api:4.16.0
  - net.kyori:adventure-platform-bukkit:4.3.2
  - net.kyori:adventure-text-minimessage:4.16.0
  - net.kyori:adventure-text-serializer-legacy:4.16.0

