name: NBUltimate
description: The ultimate NoteBlock plugin, includes a player and an editor for NBS files!
version: '${project.version}'
main: cc.cerial.nbultimate.NBUltimate
api-version: '1.20'
softdepend: [WorldGuard]
